# -*- coding: utf-8 -*-
"""Lab 01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uLutOXf_NsB2zVymKuhy4qNEV7ScdJP1

*Q1* Write a program to perform the following calculations and find the answers. $$ \sum_{x=1}^{10000} x $$
"""

def sum(start, end):
  sum = 0
  for i in range(start, end+1):
    sum += i
  return sum

print(sum(1, 10000))

"""*Q2* Write a program to perform the following calculations and find the answers.
$$ \sum_{x=1}^{100} (x^3 + 3x^2 + 5x + 9) $$
"""

def cal_equation(x):
  return pow(x,3) + 3*pow(x,2) + 5*x + 9

def sum(start, end):
  sum = 0
  for i in range(start, end+1):
    sum += cal_equation(i)
  return sum

print(sum(1, 100))

"""*Q3* Write a function “reverse” that returns the given list in reverse order"""

def reverse(xlist):
  new_list = []
  for i in range(len(xlist)-1, -1, -1):
    new_list.append(xlist[i])
  return new_list

reverse([10, 20, 30, 40, 50])

reverse(["cat", "dog", "lion", "tiger"])

